DELETE FROM `MOVIESUBTITLE` WHERE 1;
DELETE FROM `MOVIELANG` WHERE 1;
DELETE FROM `USERALBUM` WHERE 1;
DELETE FROM `USERBOOK` WHERE 1;
DELETE FROM `USERMOVIE` WHERE 1;
DELETE FROM `USERTV` WHERE 1;
DELETE FROM `USER` WHERE 1;
DELETE FROM `TRACK` WHERE 1;
DELETE FROM `ALBUM` WHERE 1;
DELETE FROM `BOOK` WHERE 1;
DELETE FROM `MOVIE` WHERE 1;
DELETE FROM `TVSHOW` WHERE 1;
DELETE FROM `ARTIST` WHERE 1;
DELETE FROM `ARTISTTYPE` WHERE 1;
DELETE FROM `LANG` WHERE 1;
DELETE FROM `STORYGENRE` WHERE 1;
DELETE FROM `SUPPORT` WHERE 1;


INSERT INTO `USER` (`ID`, `LOGIN`, `FIRSTNAME`, `LASTNAME`, `PASSWORD`, `EMAIL`, `TOKEN`) VALUES (1, 'msansm1', 'msansm1', 'bzh', '6fbd2e3d96a64f4e28faba23a7860234ba842d84', 'msansm1@test.bzh', '0277d058-f407-47d0-9e1c-797376e7da1a'), (2, 'testarq', 'test', 'arq', '6fbd2e3d96a64f4e28faba23a7860234ba842d84', 'test@arq.bzh', '0277d058-f407-47d0-9e1c-797376e7da1a34');

INSERT INTO `STORYGENRE` (`ID`, `NAME`) VALUES (1, 'Aventure'), (2, 'Action');

INSERT INTO `SUPPORT` (`ID`, `NAME`) VALUES (1, 'DVD'), (2, 'Blu-ray');

INSERT INTO `LANG` (`ID`, `NAME`) VALUES (1, 'Français'), (2, 'Anglais');

INSERT INTO `ALBUM` (`ID`, `TITLE`, `COVER`, `RELEASEDATE`, `GENRE`, `NBTRACKS`, `SUPPORT`, `ISSIGNED`) VALUES (1, 'And justice for all', NULL, '1984-12-01 00:00:00', NULL, 8, NULL, 0);

INSERT INTO `BOOK` (`ID`, `TITLE`, `EDITOR`, `COLLECTION`, `COVER`, `DESCRIPTION`, `PUBLICATIONDATE`, `GENRE`, `TYPE`, `LANG`, `ISSIGNED`, `SERIES`, `BOOKNB`, `ISSERIEDONE`) VALUES (1, 'The Hobbit', NULL, NULL, NULL, 'In a hole there was a Hobbit', '1937-05-01 00:00:00', NULL, NULL, NULL, 0, NULL, 1, NULL);

INSERT INTO `MOVIE` (`ID`, `TITLE`, `DESCRIPTION`, `RELEASEDATE`, `COVER`, `SUPPORT`, `GENRE`, `LENGTH`, `ISCOLLECTOR`) VALUES (1, 'Princesse Mononoké', NULL, '1999-12-02 00:00:00', NULL, 1, 1, NULL, 0);

INSERT INTO `TVSHOW` (`ID`, `TITLE`, `DESCRIPTION`, `RELEASEDATE`, `COVER`, `SUPPORT`, `GENRE`, `LENGTH`, `season`, `SERIES`, `ISSERIEDONE`) VALUES (1, 'Justified s01', NULL, '2010-12-02 00:00:00', NULL, NULL, NULL, NULL, 1, 'Justified', 0);

INSERT INTO `USERALBUM` (`USER`, `ALBUM`, `RATING`, `COMMENT`) VALUES ('1', '1', NULL, NULL);

INSERT INTO `USERBOOK` (`USER`, `BOOK`, `RATING`, `COMMENT`) VALUES ('1', '1', NULL, NULL);

INSERT INTO `USERMOVIE` (`USER`, `MOVIE`, `RATING`, `COMMENT`) VALUES ('1', '1', NULL, NULL);

INSERT INTO `USERTV` (`USER`, `TVSHOW`, `RATING`, `COMMENT`) VALUES ('1', '1', NULL, NULL);

INSERT INTO `MOVIELANG` (`MOVIE`, `LANG`) VALUES ('1', '1'), ('1', '2');

INSERT INTO `MOVIESUBTITLE` (`MOVIE`, `SUBTITLE`) VALUES ('1', '1'), ('1', '2');
