DELETE FROM `MOVIESUBTITLE` WHERE 1;
DELETE FROM `MOVIELANG` WHERE 1;
DELETE FROM `USERALBUM` WHERE 1;
DELETE FROM `USERBOOK` WHERE 1;
DELETE FROM `USERMOVIE` WHERE 1;
DELETE FROM `USERTV` WHERE 1;
DELETE FROM `ALBUMARTIST` WHERE 1;
DELETE FROM `TRACKARTIST` WHERE 1;
DELETE FROM `BOOKARTIST` WHERE 1;
DELETE FROM `MOVIEARTIST` WHERE 1;
DELETE FROM `USER` WHERE 1;
DELETE FROM `TRACK` WHERE 1;
DELETE FROM `ALBUM` WHERE 1;
DELETE FROM `BOOK` WHERE 1;
DELETE FROM `MOVIE` WHERE 1;
DELETE FROM `TVSHOW` WHERE 1;
DELETE FROM `ARTIST` WHERE 1;
DELETE FROM `ARTISTTYPE` WHERE 1;
DELETE FROM `LANG` WHERE 1;
DELETE FROM `STORYGENRE` WHERE 1;
DELETE FROM `SUPPORT` WHERE 1;
DELETE FROM `EDITOR` WHERE 1;
DELETE FROM `COLLECTION` WHERE 1;
DELETE FROM `BOOKTYPE` WHERE 1;
DELETE FROM `GENRE` WHERE 1;
DELETE FROM `CONFIGURATION` WHERE 1;
DELETE FROM `DATABASE` WHERE 1;

ALTER TABLE `ARTIST` AUTO_INCREMENT = 1;
ALTER TABLE `TVSHOW` AUTO_INCREMENT = 1;
ALTER TABLE `USER` AUTO_INCREMENT = 1;

INSERT INTO `DATABASE` (`ID`, `VERSION`) VALUES (NULL, '0.7');

INSERT INTO `CONFIGURATION` (`PARAMETER`, `VALUE`) VALUES ('filesystem', '/opt/medek/fs/');

INSERT INTO `USER` (`ID`, `LOGIN`, `PASSWORD`, `EMAIL`, `TOKEN`, `MOBILE_TOKEN`) VALUES (1, 'msansm1', '6fbd2e3d96a64f4e28faba23a7860234ba842d84', 'msansm1@test.bzh', '0277d058-f407-47d0-9e1c-797376e7da1a', null), (2, 'testarq', '6fbd2e3d96a64f4e28faba23a7860234ba842d84', 'test@arq.bzh', '0277d058-f407-47d0-9e1c-797376e7da1a34', null);

INSERT INTO `STORYGENRE` (`ID`, `NAME`) VALUES (1, 'Aventure'), (2, 'Action');

INSERT INTO `SUPPORT` (`ID`, `NAME`) VALUES (1, 'DVD'), (2, 'Blu-ray'), (3, 'CD'), (4, 'Dématérialisé');

INSERT INTO `LANG` (`ID`, `NAME`) VALUES (1, 'Français'), (2, 'Anglais');

INSERT INTO `EDITOR` (`ID`, `NAME`) VALUES (1, 'Dupuis'), (2, 'Livre de Poche');

INSERT INTO `COLLECTION` (`ID`, `NAME`) VALUES (1, 'Yoko Tsuno'), (2, 'Le Disque Monde');

INSERT INTO `BOOKTYPE` (`ID`, `NAME`) VALUES (1, 'Roman'), (2, 'B.D.');

INSERT INTO `GENRE` (`ID`, `NAME`) VALUES (1, 'Metal'), (2, 'Rock');

INSERT INTO `ARTISTTYPE` (`ID`, `NAME`) VALUES (1, 'Groupe de musique'), (2, 'Auteur'), (3, 'Producteur'), (4, 'Réalisateur'), (5, 'Scénariste');

INSERT INTO `ARTIST` (`ID`, `NAME`, `FIRSTNAME`, `TYPE`, `NATIONALITY`, `PICTURE`, `BIOLINK`) VALUES (1, 'Metallica', NULL, '1', 'Americain', NULL, NULL), (2, 'Tolkien', 'JRR', '2', 'Anglais', NULL, NULL), (3, 'Miyasaki', 'Hayao', '3', 'Japonais', NULL, NULL);

INSERT INTO `ALBUM` (`ID`, `TITLE`, `COVER`, `RELEASEDATE`, `GENRE`, `NBTRACKS`, `SUPPORT`) VALUES (1, 'And justice for all', NULL, '1984-12-01 00:00:00', 1, 8, 3);

INSERT INTO `TRACK` (`ID`, `ALBUM`, `TITLE`, `NUMBER`, `LENGTH`) VALUES (1, '1', 'Master of Puppets', '3', '7:50'), (2, '1', 'Orion', '8', '9:57');

INSERT INTO `ALBUMARTIST` (`ALBUM`, `ARTIST`, `TYPE`) VALUES ('1', '1', NULL);

INSERT INTO `TRACKARTIST` (`TRACK`, `ARTIST`, `TYPE`) VALUES ('1', '1', NULL), ('2', '1', NULL);

INSERT INTO `BOOK` (`ID`, `TITLE`, `EDITOR`, `COLLECTION`, `COVER`, `DESCRIPTION`, `PUBLICATIONDATE`, `GENRE`, `TYPE`, `LANG`, `SERIES`, `BOOKNB`, `ISSERIEDONE`) VALUES (1, 'The Hobbit', 2, NULL, NULL, 'In a hole there was a Hobbit', '1937-05-01 00:00:00', 1, 1, 2, NULL, 1, 1);

INSERT INTO `BOOKARTIST` (`BOOK`, `ARTIST`, `TYPE`) VALUES ('1', '2', NULL);

INSERT INTO `MOVIE` (`ID`, `TITLE`, `DESCRIPTION`, `RELEASEDATE`, `COVER`, `SUPPORT`, `GENRE`, `LENGTH`, `ISCOLLECTOR`) VALUES (1, 'Princesse Mononoké', NULL, '1999-12-02 00:00:00', NULL, 1, 1, NULL, 0);

INSERT INTO `MOVIEARTIST` (`MOVIE`, `ARTIST`, `TYPE`) VALUES ('1', '3', NULL);

INSERT INTO `MOVIELANG` (`MOVIE`, `LANG`) VALUES ('1', '1'), ('1', '2');

INSERT INTO `MOVIESUBTITLE` (`MOVIE`, `SUBTITLE`) VALUES ('1', '1'), ('1', '2');

INSERT INTO `TVSHOW` (`ID`, `TITLE`, `DESCRIPTION`, `RELEASEDATE`, `COVER`, `SUPPORT`, `GENRE`, `LENGTH`, `season`, `SERIES`, `ISSERIEDONE`) VALUES (1, 'Justified s01', NULL, '2010-12-02 00:00:00', NULL, NULL, NULL, NULL, 1, 'Justified', 0);

INSERT INTO `USERALBUM` (`USER`, `ALBUM`, `ISSIGNED`, `RATING`, `COMMENT`) VALUES ('1', '1', 0, NULL, NULL);

INSERT INTO `USERBOOK` (`USER`, `BOOK`, `ISSIGNED`, `RATING`, `COMMENT`) VALUES ('1', '1', 0, NULL, NULL);

INSERT INTO `USERMOVIE` (`USER`, `MOVIE`, `RATING`, `COMMENT`) VALUES ('1', '1', NULL, NULL);

INSERT INTO `USERTV` (`USER`, `TVSHOW`, `RATING`, `COMMENT`) VALUES ('1', '1', NULL, NULL);
